import { SK, US } from "country-flag-icons/react/1x1"
import { supportsFlagEmoji } from "./emojiSupport";

export type languageKey = keyof typeof table;
export type textKey = keyof typeof table[languageKey];


export const table = {
    sk: {
        LOGIN: "Prihlásiť",
        COMMENT_COUNT_S: "Komentár",
        COMMENT_COUNT_P: "Komentárov",
        CREATE: "Vytvoriť",
        SEARCH: "Vyhľadávať",
        SEARCH_IN: "Vyhľadávať ",
        COMMUNITIES: "v Komunitách",
        POSTS: "v Príspevkoch",
        USERS: "medzi Používateľmi",
        PROFILE: "Profil",
        LOG_OUT: "Odhlásiť sa",
        CREATE_POST: "Vytvoriť príspevok",
        HOME: "Domovská stránka",
        HOME_DESCRIPTION: "vaša titulná stránka",
        CREATE_COMMUNITY: "Vytvoriť komunitu",
        USEFUL_LINKS: "Užitočné Odkazy",
        CONTACT: "Kontaktujte nás",
        PRIVACY_POLICY: "Zásady ochrany osobných údajov",
        TERMS_OF_SERVICE: "Podmienky služby",
        NEWSLETTER: "Odber Noviniek",

        SECONDS_L: "sekundami",
        MINUTES_L: "minútami",
        HOURS_L: "hodinami",
        DAYS_L: "dňami",
        MONTHS_L: "mesiacmi",
        YEARS_L: "rokmi",
        SECONDS_S: "s",
        MINUTES_S: "min",
        HOURS_S: "hod",
        DAYS_S: "d",
        MONTHS_S: "m",
        YEARS_S: "r",
        AGO: "pred",

        LOCK: "Zamknúť",
        LOCKED_DESCRIPTION: "Tento príspevok bol zamknutý moderátormi tejto komunity",
        UNLOCK: "Odomknúť",
        DELETE: "Zmazať",

        CREATE_COMMUNITY_DESCRIPTION: "Vytvorte miesto pre ľudí s podobnými záujmami",
        COMMUNITY_NAME: "Meno Komunity",
        COMMUNITY_DESCRIPTION: "Popis komunity",
        COMMUNITY_DESCRIPTION_PLACEHOLDER: "O čom je táto komunita?",
        COMMUNITY_ERROR_FORMAT: "meno komunity musí obsahovať len písmená, čísla a podržníky",
        COMMUNITY_ERROR_EXISTS: "komunita s rovnakým menom už existuje",
        COMMUNIT_ERROR_LENGTH: "meno komunity nesmie mať viac ako 40 znakov",

        NEWSLETTER_SUBSCRIBE_TITLE: "Prihláste sa ku odberu noviniek!",
        NEWSLETTER_SUBSCRIBE: "Odoberať",
        NEWSLETTER_SUBSCRIBE_SUCCESS: "Úspešne ste sa prihlásili na odber nášho newslettera! Skontrolujte si doručenú poštu a potvrďte svoj e-mail.",
        NEWSLETTER_ALREADY_SUBCRIBED: "Táto emailová adresa už je prihlásená na odber noviniek",
        NEWSLETTER_DESCRIPTION: "Dostávajte exkluzívne aktualizácie a užitočný obsah priamo do vašej schránky",

        INVALID_EMAIL: "Zadajte platnú emailovú adresu",
        FIELD_REQUIRED: "Toto pole je povinné",
        ERROR_GENERIC: "Niečo sa pokazilo",

        PASSWORD: "Heslo",
        PASSWORD_PLACEHOLDER: "Zadajte vaše heslo",
        LOGIN_BUTTON: "Prihlásiť sa",
        ADDITIONAL_LOGIN_OPTIONS: "ALEBO POKRAČUJTE CEZ",
        REGISTER_PROMPT: "Ešte nemáte u nás účet?",
        REGISTER_HERE: "Zaregistrujte sa tu.",
        INCORRECT_CREDENTIALS: "nesprávne prihlasovacie údaje",

        FIRST_NAME: "Meno",
        LAST_NAME: "Priezvisko",
        USER_NAME: "Užívateľské meno",
        CONFIRM_PASSWORD: "Potvrdiť heslo",
        ACCEPT: "Prijímam",
        AND: "a",
        USERNAME_SHORT: "Užívateľské meno musí byť dlhé aspoň 3 znaky",
        USERNAME_LONG: "Užívateľské meno nesmie byť dlhšie ako 25 znakov",
        USERNAME_FORMAT: "Užívateľské meno musí obsahovať len písmená, čísla a podtržníky",
        PASSWORD_SHORT: "Heslo musí byť aspoň 6 znakov dlhé",
        PASSWORD_MISMATCH: "Heslá sa nezhodujú",
        AGREE_ERROR: "Musíte súhlasiť s podmienkami služby a zásadami ochrany osobných údajov",

        COMMUNITY: "Komunita",
        SEARCH_COMMUNITIES: "Vyhľadávať komunity...",
        SELECT_COMMUNITIES: "Vyberte komunitu",
        MY_COMMUNITIES: "Moje komunity",
        OTHERS: "Ostatné",
        NO_COMMUNITIES: "Nenašli sme žiadne komunity.",
        MEMBERS: "členov",
        TAG: "ŠTÍTOK",
        SEARCH_TAGS: "Vyhľadávať štítky...",
        NO_TAGS: "Nenašli sme žiadne štítky.",
        TITLE: "Hlavička",
        BODY: "Telo",
        BODY_PLACEHOLDER: "Sem napíšte telo príspevku.",
        REQUIRED: "Povinné pole",
        TITLE_LONG: "Hlavička nesmie mať viac ako 100 znakov.",
        TITLE_SHORT: "Hlavička musí mať viac ako 6 znakov.",
        BODY_LONG: "Telo nesmie mať viac ako 700 znakov.",
        SUBMIT: "Odoslať",
        UPLOAD_IMAGE: "Nahrať obrázok",

        COMMMUNITIES_P: "Komunity",
        POSTS_P: "Príspevky",
        POSTS_L: "Príspevkov",
        USERS_P: "Používatelia",

        NO_SEARCH: "Žiadne výsledky vyhľadávania pre",
        NO_SEARCH_TEXT: "Skúste upraviť kľúčové slová alebo filter, aby ste našli to, čo hľadáte.",

        JOIN: "Pridať sa",
        LEAVE: "Odísť",
        JOINED: "Vstúpili ste do komunity 'COMMUNITY' ako člen",
        LEFT: "Opustili ste komunitu 'COMMUNITY' ako člen",
        ABOUT_COMMUNITY: "O komunite",
        TAGS: "Štítky",
        TAGS_TEXT: "Toto sú štítky používané na filtrovanie príspevkov",
        ADD_TAG: "Pridať Štítok",
        NAME: "Názov",
        NAME_LONG: "Názov nemôže byť dlhší ako 15 znakov.",
        COLOR: "Farba",
        MODERATORS: "Moderátori",
        MODERATORS_TEXT: "Toto sú ľudia, ktorí presadzujú pravidlá tejto komunity",
        ADD_MODERATOR: "Pridať moderátora",
        NO_USERS: "Nenašli sme žiadnych používateľov",
        SORT_BY: "Zoradiť podľa",
        NEWEST: "Najnovšie",
        BEST: "Najlepšie",
        TODAY: "Dnes",
        WEEK: "Tento Týždeň",
        MONTH: "Tento Mesiac",
        YEAR: "Tento Rok",
        ALL_TIME: "Vždy",
        COMMUNITY_ABOUT: "O komunite",
        COMMUNITY_NO_TAGS: "Pre túto komunitu neexistujú žiadne štítky. Požiadajte moderátorov tejto komunity, aby ich pridali",
        MEMBER: "členov",

        ALREADY_MOD: "Tento používateľ je už moderátorom tejto komunity.",
        ADD_MOD_CONFIRM: "Naozaj chcete pridať používateľa ako moderátora?",
        ADD_MOD_CONFIRM_TEXT: "Ste si istý, že chcete pridať používateľa 'USER' ako moderátora tejto komunity?",
    },
    en: {
        LOGIN: "Login",
        COMMENT_COUNT_S: "Comment",
        COMMENT_COUNT_P: "Comments",
        CREATE: "Create",
        SEARCH: "Search",
        SEARCH_IN: "Search",
        COMMUNITIES: "in Communities",
        POSTS: "in Posts",
        USERS: "in Users",
        PROFILE: "Profile",
        LOG_OUT: "Log out",
        CREATE_POST: "Create a Post",
        HOME: "Home",
        HOME_DESCRIPTION: "This is your front page",
        CREATE_COMMUNITY: "Create a Community",
        USEFUL_LINKS: "Useful Links",
        CONTACT: "Contact Us",
        PRIVACY_POLICY: "Privacy Policy",
        TERMS_OF_SERVICE: "Terms of Service",
        NEWSLETTER: "Newsletter",
        SECONDS_L: "Seconds",
        MINUTES_L: "Minutes",
        HOURS_L: "Hours",
        DAYS_L: "Days",
        MONTHS_L: "Months",
        YEARS_L: "Years",
        SECONDS_S: "s",
        MINUTES_S: "m",
        HOURS_S: "h",
        DAYS_S: "d",
        MONTHS_S: "m",
        YEARS_S: "y",
        AGO: "ago",

        LOCK: "lock",
        LOCKED_DESCRIPTION: "This post has been locked by the moderators of this community",
        UNLOCK: "unlock",
        DELETE: "delete",

        CREATE_COMMUNITY_DESCRIPTION: "Create a place for people with similar interest.",
        COMMUNITY_NAME: "Community Name",
        COMMUNITY_DESCRIPTION: "Community Description",
        COMMUNITY_DESCRIPTION_PLACEHOLDER: "What is this community about?",
        COMMUNITY_ERROR_FORMAT: "name must only contain letters and numbers and underscore",
        COMMUNITY_ERROR_EXISTS: "community already exists",
        COMMUNIT_ERROR_LENGTH: "community name must contain at most 40 characters",

        NEWSLETTER_SUBSCRIBE_TITLE: "Subscribe To Our Newsletter!",
        NEWSLETTER_SUBSCRIBE: "Subscribe",
        NEWSLETTER_SUBSCRIBE_SUCCESS: "Successfully signed up to our newsletter! Check you inbox to confirm your e-mail.",
        NEWSLETTER_ALREADY_SUBCRIBED: "Email is already signed up for this newsletter",
        NEWSLETTER_DESCRIPTION: "Receive exclusive updates, insightful content delivered directly to your inbox",

        INVALID_EMAIL: "Enter a valid email address",
        FIELD_REQUIRED: "This field is required",
        ERROR_GENERIC: "something went wrong.",

        PASSWORD: "Password",
        PASSWORD_PLACEHOLDER: "Enter your password",
        LOGIN_BUTTON: "Log In",
        ADDITIONAL_LOGIN_OPTIONS: "OR CONTINUE WITH",
        REGISTER_PROMPT: "Don't have an account?",
        REGISTER_HERE: "Register here.",
        INCORRECT_CREDENTIALS: "Email or Password is incorrect",

        FIRST_NAME: "First Name",
        LAST_NAME: "Last Name",
        USER_NAME: "User Name",
        CONFIRM_PASSWORD: "Confirm Password",
        ACCEPT: "Accept",
        AND: "and",
        USERNAME_SHORT: "Your username has to be at least 3 characters long",
        USERNAME_LONG: "Your username cannot be longer than 25 characters",
        USERNAME_FORMAT: "Your username has to contain only letters, numbers or underscores",
        PASSWORD_SHORT: "Password must be at least 6 characters long",
        PASSWORD_MISMATCH: "Passwords don't match",
        AGREE_ERROR: "You must agree to the terms and conditions and privacy policy",

        COMMUNITY: "Community",
        SEARCH_COMMUNITIES: "Search communities...",
        MY_COMMUNITIES: "My communities",
        OTHERS: "Others",
        SELECT_COMMUNITIES: "Select communities",
        NO_COMMUNITIES: "No communities found.",
        MEMBERS: "members",
        TAG: "TAG",
        SEARCH_TAGS: "Search tags...",
        NO_TAGS: "No tags found.",
        TITLE: "Title",
        BODY: "Body",
        BODY_PLACEHOLDER: "Type your message here.",
        REQUIRED: "Required Field",
        TITLE_LONG: "Title must not exceed 100 characters.",
        TITLE_SHORT: "Title must contain at least 6 characters.",
        BODY_LONG: "Body must not exceed 700 characters.",
        SUBMIT: "Submit",
        UPLOAD_IMAGE: "Upload an image",

        COMMMUNITIES_P: "Communities",
        POSTS_P: "Posts",
        USERS_P: "Users",
        POSTS_L: "Posts",

        NO_SEARCH: "No Search Results for",
        NO_SEARCH_TEXT: "Try adjusting your keywords or filter to find what you're looking for.",

        JOIN: "Join",
        LEAVE: "Leave",
        JOINED: "Joined community 'COMMUNITY' as a member",
        LEFT: "Left community 'COMMUNITY' as a member",
        ABOUT_COMMUNITY: "About community",
        TAGS: "Tags",
        TAGS_TEXT: "These are the tags used for filtering posts",
        ADD_TAG: "Add Tag",
        NAME: "Name",
        COLOR: "Color",
        MODERATORS: "Moderators",
        MODERATORS_TEXT: "These are the people that enforce the rules of this community",
        ADD_MODERATOR: "Add Moderator",
        NO_USERS: "No users found",
        SORT_BY: "Sort By",
        NEWEST: "Newest",
        BEST: "Best",
        TODAY: "Today",
        WEEK: "This Week",
        MONTH: "This Month",
        YEAR: "This Year",
        ALL_TIME: "All Time",
        COMMUNITY_ABOUT: "About",
        COMMUNITY_NO_TAGS: "There are no tags for this community. Ask the moderators of this community to add them",
        MEMBER: "member",

        NAME_LONG: "Name cannot be longer than 15 characters.",
        ALREADY_MOD: "This user is already a moderator of this community.",

        ADD_MOD_CONFIRM: "Are you sure you want to add a user as a moderator?",
        ADD_MOD_CONFIRM_TEXT: "Are you sure that you want to add the user 'USER' as a moderator of this community?",
    }
}
const supports_flag = supportsFlagEmoji();
type locales_type = {
    name: "sk" | "en",
    text: string,
    Flag: JSX.Element
}[]
export const locales:locales_type = [
    { name: "sk", text: "Slovak", Flag: supports_flag ? <>🇸🇰 </> : <SK className="h-4 aspect-video inline mr-1"/>},
    { name: "en",text: "English", Flag: supports_flag ? <>🇺🇸 </> : <US className="h-4 aspect-video inline mr-1"/>}
]

//[{f:""}, {f: ""}]